import styles from './globals.css'
import Link from 'next/link'



export const metadata = {
  title: 'React Services',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={styles.body}>
        <header className={styles.header}>
          <h1>Servicios con React.js</h1>
        </header>
        <nav className={styles.nav}>
          <Link href={'/'}>Carts</Link>
          <Link href={'/newcart'}>New Carts</Link>
          <Link href={'/products'}>Products</Link>
          <Link href={'/newproduct'}>New Product</Link>
        </nav>
        <main className={styles.main}>
          {children}
        </main>

        <footer className={styles.footer}>
          <h3>Luis Miguel Guerrero @2023</h3>
        </footer>


      
      </body>
    </html>
  )
}
